Repository vultr/govultr, pull requests merged in 2019-07, with the labels that each got.

#19 Update to the latest Go releases
  .travis.yml
Labels: enhancement

#20 Fix panic on request failure
  govultr.go
  govultr_test.go
Labels: bug

#21 Release for v0.1.4
  CHANGELOG.md
  govultr.go
Labels: release
