Repository vultr/govultr, pull requests merged in 2021-12, with the labels that each got.

#192 [Bug] : fix plan types to handle brazil
  plans.go
Labels: bug

#193 release : v2.12.0
  CHANGELOG.md
  govultr.go
Labels: release

#194 Add autoreleaser workflow
  .github/workflows/notify-release.yml
  .github/workflows/releaser.yml
  .goreleaser.yml
Labels: enhancement
