Repository vultr/govultr, pull requests merged in 2022-03, with the labels that each got.

#206 Restore v2 endpoint fix
  instance.go
  instance_test.go
Labels: bug

#207 Release 2.14.2 #patch
  CHANGELOG.md
  govultr.go
Labels: release

#208 bumping go 1.16 to 1.17
  .github/workflows/gochecks.yml
  .github/workflows/releaser.yml
  go.mod
Labels: dependencies
