Repository vultr/govultr, pull requests merged in 2022-04, with the labels that each got.

#209 block storage: adding block type
  block_storage.go
  block_storage_test.go
Labels: enhancement

#210 Add Vultr VPC support
  govultr.go
  instance.go
  instance_test.go
  load_balancer.go
  load_balancer_test.go
  network.go
  vpc.go
  vpc_test.go
Labels: enhancement

#211 Release v2.15.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release

#212 block type omit
  block_storage.go
Labels: bug

#216 Firewall Rules : adding `ip_type`
  firewall_rule.go
  firewall_rule_test.go
Labels: enhancement

#217 Kubernetes: upgrade support
  kubernetes.go
  kubernetes_test.go
Labels: enhancement
