Repository vultr/govultr, pull requests merged in 2023-12, with the labels that each got.

#288 Add support for Managed Database user access control for Redis
  database.go
Labels: enhancement

#290 Update the README with non-auth client examples
  README.md
Labels: documentation

#291 Support Marketplace App Variables
  bare_metal_server.go
  govultr.go
  instance.go
  marketplace.go
  marketplace_test.go
Labels: enhancement

#292 Release v3.6.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release
