Repository vultr/govultr, pull requests merged in 2023-03, with the labels that each got.

#239 Fix context error in govultr test
  .github/workflows/coverage.yml
  govultr_test.go
Labels: bug

#238 Add support for Vultr Managed Databases
  database.go
  database_test.go
  govultr.go
Labels: enhancement

#241 Update Go to v1.20
  .gitignore
  go.mod
Labels: dependencies

#242 Release v3.0.0 #major
  CHANGELOG.md
  govultr.go
Labels: release

#243 Release v3.0.1 #patch
  CHANGELOG.md
  README.md
  go.mod
Labels: release

#245 Release v3.0.2 #patch
  CHANGELOG.md
Labels: release
