Repository vultr/govultr, pull requests merged in 2023-10, with the labels that each got.

#267 Add deprecation notice to v1 README
  .codecov.yml
  .github/workflows/codeql-analysis.yml
  .travis.yml
  README.md
Labels: documentation

#266 Remove references to deprecated V1 API
  CHANGELOG.md
  README.md
  govultr.go
Labels: documentation

#268 Add support for Managed Database public/private hostnames
  database.go
  database_test.go
Labels: enhancement

#269 Release v3.3.2 #patch
  CHANGELOG.md
  govultr.go
Labels: release

#270 Convert DatabaseUpdate VPCID to pointer for empty values
  database.go
Labels: bug

#271 Release v3.3.3 #patch
  CHANGELOG.md
  govultr.go
Labels: release

#272 Add support for DBaaS FerretDB offering
  database.go
Labels: enhancement

#273 Add HA control planes support for VKE
  kubernetes.go
Labels: enhancement
