Repository vultr/govultr, pull requests merged in 2023-11, with the labels that each got.

#276 Support read replica promotion for Managed Databases
  database.go
Labels: enhancement

#277 Add managed firewall support for VKE
  kubernetes.go
Labels: enhancement

#278 Add support for container registry operations
  .golangci.yaml
  container_registry.go
  container_registry_test.go
  govultr.go
  kubernetes.go
  kubernetes_test.go
  object_storage.go
Labels: enhancement

#281 Release v3.4.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release

#284 Container registry data fixes
  container_registry.go
  container_registry_test.go
Labels: bug

#282 Add support for Managed Database usage endpoint
  database.go
Labels: enhancement

#285 Release v3.4.1 #patch
  CHANGELOG.md
  govultr.go
Labels: release

#287 Add disable IPv4 option to instance create request
  instance.go
Labels: enhancement
