Repository vultr/govultr, pull requests merged in 2024-06, with the labels that each got.

#314 Update golangci-lint and enable most go-vet checks
  .github/workflows/gochecks.yml
  .golangci.yaml
Labels: automation

#315 Add Support for Vultr Serverless Inference
  database.go
  govultr.go
  inference.go
  inference_test.go
Labels: enhancement

#316 Release v2.8.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release

#318 Release v2.8.1 #patch
  CHANGELOG.md
  govultr.go
Labels: release

#319 Add support for CDN
  cdn.go
  govultr.go
Labels: enhancement

#320 Release v3.9.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release
