Repository vultr/govultr, pull requests merged in 2024-05, with the labels that each got.

#307 Fix mattermost notifications
  .github/workflows/notify-issue.yml
  .github/workflows/notify-pr.yml
  .github/workflows/releaser.yml
Labels: automation

#310 [Feature] add MdiskMode to BareMetalCreate and BareMetalUpdate structs
  bare_metal_server.go
Labels: enhancement

#311 Release v3.7.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release
