Repository vultr/govultr, pull requests merged in 2024-10, with the labels that each got.

#325 Add http2/3 and timeout options to load balancers
  load_balancer.go
Labels: enhancement

#326 Add vanity domain and SSL options to CDN
  cdn.go
Labels: enhancement

#327 Remove deprecated Tag and Type fields
  bare_metal_server.go
  firewall_rule.go
  firewall_rule_test.go
  instance.go
Labels: clean-up

#328 Add instance user scheme field
  instance.go
Labels: enhancement

#329 Add support for sub-accounts
  govultr.go
  subaccount.go
Labels: enhancement

#330 Fix CDN structs and endpoint
  cdn.go
Labels: bug

#331 Fix base struct for subaccount create
  subaccount.go
Labels: bug

#332 Add CDN & Sub-account tests
  cdn_test.go
  subaccount_test.go
Labels: automation

#333 Update go from v1.21 to v1.23
  go.mod
  go.sum
Labels: dependencies

#334 Update github workflows to go 1.23
  .github/workflows/coverage.yml
  .github/workflows/gochecks.yml
  .github/workflows/releaser.yml
Labels: automation

#335 Add user scheme to bare metal
  bare_metal_server.go
Labels: enhancement

#336 Release v3.10.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release

#337 Support Managed Kafka
  database.go
  database_test.go
Labels: enhancement

#338 Remove deprecated exportloopref linter
  .golangci.yaml
Labels: automation

#339 Add Github CODEOWNERS file
  .github/CODEOWNERS
Labels: automation

#340 Release v3.11.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release

#341 Fix Quota Create endpoint param for Kafka
  database.go
Labels: bug

#342 Release v3.11.1 #patch
  CHANGELOG.md
  govultr.go
Labels: release

#343 Fix Managed Kafka Advanced Config Field Naming
  database.go
Labels: bug

#344 Release v3.11.2 #patch
  CHANGELOG.md
  govultr.go
Labels: release
