Repository vultr/govultr, pull requests merged in 2025-01, with the labels that each got.

#350 Add AutoSSL and GlobalRegions to load balancers
  load_balancer.go
Labels: enhancement

#351 Release v3.14.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release

#352 Add missing load balancer SSL fields and AutoSSL struct
  load_balancer.go
Labels: bug

#353 Release v3.14.1 #patch
  CHANGELOG.md
  govultr.go
Labels: release
