Repository vultr/govultr, pull requests merged in 2025-03, with the labels that each got.

#360 Update Go from v1.23 to v1.24
  .github/workflows/coverage.yml
  .github/workflows/gochecks.yml
  .github/workflows/releaser.yml
  go.mod
Labels: dependencies

#361 Release v3.15.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release

#364 Add go doc deprecation for VPC2 service and structs
  govultr.go
  vpc2.go
Labels: documentation, clean-up

#365 Add object storage tiers
  object_storage.go
Labels: enhancement

#367 Reset min go.mod go version to v1.23
  go.mod
Labels: dependencies, clean-up

#368 Release v3.16.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release

#369 Make object storage requests use value struct
  object_storage.go
  object_storage_test.go
Labels: bug

#370 Release v3.16.1 #patch
  CHANGELOG.md
  govultr.go
Labels: release

#363 Add taints to node pools
  kubernetes.go
  kubernetes_test.go
Labels: enhancement

#372 Add iPXE URL to bare metal
  bare_metal_server.go
Labels: enhancement

#375 Release v3.18.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release
