Repository vultr/govultr, pull requests merged in 2025-08, with the labels that each got.

#391 Add node pool user_data to create/update structs
  kubernetes.go
Labels: enhancement, Review effort 1/5

#392 Release v3.22.0 #minor
  CHANGELOG.md
  govultr.go
Labels: release, Review effort 1/5

#390 snapshots: Add support for CreateFromURL UEFI field
  snapshot.go
Labels: enhancement
